name: Daily Lithium Price Scraper

on:
  schedule:
    - cron: '16 8 * * *'  # 16:03 SGT
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install selenium pandas chromedriver-autoinstaller

      - name: Install latest Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb

      - name: Run scraper
        run: python smm_usd_price_scraper.py

      - name: Commit updated CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
          if [ -f "usd_lithium_price.csv" ]; then
            git add usd_lithium_price.csv
            git diff --cached --quiet || git commit -m "Daily update: $(date +'%Y-%m-%d')"
            git push
          else
            echo "CSV file not found – skipping commit"
          fi
